- name: install dependencies package - Debian
  become: yes
  package:
    state: present
    name:
      - make
      - gcc
      - git
      - wget
      - curl
      - patch
      - sudo
      - libc6-dev
