- name: install dependencies package - RedHat, except Fedora
  when: ansible_distribution != 'Fedora'
  become: yes
  package:
    state: installed
    name:
      - perl-ExtUtils-MakeMaker
      - make
      - gcc
      - git
      - wget
      - patch

- name: install dependencies package - RedHat, distro Fedora
  when: ansible_distribution == 'Fedora'
  become: yes
  package:
    state: latest
    name:
      - perl-ExtUtils-MakeMaker
      - make
      - gcc
      - git-all
      - wget
      - patch
      - tar
